apiVersion: v1
baseDomain: example.com
metadata:
  name: ocp

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYWU4MjQ3OTBkOWY0NGFiOWFjZjVjNTk4ZjY1N2IzNDc6SEJaUFo2TFM5WTVIOFREVElNVkoyMDdOVllaRVg2WFBLU05XQkRDRVJXMDNZVVM2REM3WlROWDYxR0tTNVVCTA==","email":"chetan@prodevans.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYWU4MjQ3OTBkOWY0NGFiOWFjZjVjNTk4ZjY1N2IzNDc6SEJaUFo2TFM5WTVIOFREVElNVkoyMDdOVllaRVg2WFBLU05XQkRDRVJXMDNZVVM2REM3WlROWDYxR0tTNVVCTA==","email":"chetan@prodevans.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTU4NDI5YmZjLTA2MTMtNDdmYy04YTdhLThhOGI2Y2NlMzhkNjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXlZbUUyWmpneU9HUXdORGswTURjM1ltTmpZVEUyTnpJeVptWmlNREJpTnlKOS5nM084SW5BUDZzYzdQVzBZWDRRTnRoaHpwWXdMSzJyUWdNQ2FDMjRpQ0YzMUdDQlR5NnBVYlJwTDVtVnZkSExlR1lCemJOaGZfc21OdVpiNkp5LVA3ZGZLX0ZZWDA3WkRteTF1LUJvdHBFSUVUN1lxdDFwV283a3ktOHM0emJBMXpwV24yelc1T2VfcEc2NFhuaC1HUzZEOFV1OHFRSXk1YzlRLWh0Y0tvUlUyWlllZXpJNFpLTU5xTWUteUdCZGxVLUVqQ1BRallMRDBGdVJwUWp3R3czc2xQQXFwZ19OQl8zZnVWaHA5S3hhX2paV21uZFFkTHh2aDZXT1NOMm5BS1hrdGZSajctS1RBR2dNaGhwY2hXcUVoOEs4Nzh2dy01QmZvQVdqWDJKTXY1T2pyckY4NWhTVko5VXFVVHVMcVJQN1BOa0VrcmM4cFJHeW5XQkRqSmhVbkVSWFJ2UTB4dXViMzdKSHpveDcyTWdTTUxCb2liNnVsb1hQdE1zX0lWTkFNX2JVSklRWjNaVERLd0FiMGg3RWZqOXRtbnBpNmlFNF8wTW9WVzY1Q2FXR3dYeG1VeGthMlBjUzZkNWhjcW15XzZ1RDZWZGhaNFNPZ1BST1BZVFJLRzFQUzY4aF9yUmJsdFdIRjAtUVVtUEVuUzhfNG5CcmoyLVpxNzB2blJ2LUtPRkQtaEtjNGtRUmdXbkRGdDJFaVFZRHNyV1lqblFUQmxOd1VKd0ZjVnRDbUJtVWt3MElCWlVtN25oMlQ5SGxXQ1ZYcFhuY0JxME1JZ1ZSZXVrMkctVG9GYnVnRUVNR3dEYmxxZVREOWhqajNEOF9mSmlwVTk0S2djTHVRMmUtckxqa2pESldGSTl6UkUzYnd0V3ROZXh5Z0ZnODNLYWdvX0J3Vzd2SQ==","email":"chetan@prodevans.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTU4NDI5YmZjLTA2MTMtNDdmYy04YTdhLThhOGI2Y2NlMzhkNjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXlZbUUyWmpneU9HUXdORGswTURjM1ltTmpZVEUyTnpJeVptWmlNREJpTnlKOS5nM084SW5BUDZzYzdQVzBZWDRRTnRoaHpwWXdMSzJyUWdNQ2FDMjRpQ0YzMUdDQlR5NnBVYlJwTDVtVnZkSExlR1lCemJOaGZfc21OdVpiNkp5LVA3ZGZLX0ZZWDA3WkRteTF1LUJvdHBFSUVUN1lxdDFwV283a3ktOHM0emJBMXpwV24yelc1T2VfcEc2NFhuaC1HUzZEOFV1OHFRSXk1YzlRLWh0Y0tvUlUyWlllZXpJNFpLTU5xTWUteUdCZGxVLUVqQ1BRallMRDBGdVJwUWp3R3czc2xQQXFwZ19OQl8zZnVWaHA5S3hhX2paV21uZFFkTHh2aDZXT1NOMm5BS1hrdGZSajctS1RBR2dNaGhwY2hXcUVoOEs4Nzh2dy01QmZvQVdqWDJKTXY1T2pyckY4NWhTVko5VXFVVHVMcVJQN1BOa0VrcmM4cFJHeW5XQkRqSmhVbkVSWFJ2UTB4dXViMzdKSHpveDcyTWdTTUxCb2liNnVsb1hQdE1zX0lWTkFNX2JVSklRWjNaVERLd0FiMGg3RWZqOXRtbnBpNmlFNF8wTW9WVzY1Q2FXR3dYeG1VeGthMlBjUzZkNWhjcW15XzZ1RDZWZGhaNFNPZ1BST1BZVFJLRzFQUzY4aF9yUmJsdFdIRjAtUVVtUEVuUzhfNG5CcmoyLVpxNzB2blJ2LUtPRkQtaEtjNGtRUmdXbkRGdDJFaVFZRHNyV1lqblFUQmxOd1VKd0ZjVnRDbUJtVWt3MElCWlVtN25oMlQ5SGxXQ1ZYcFhuY0JxME1JZ1ZSZXVrMkctVG9GYnVnRUVNR3dEYmxxZVREOWhqajNEOF9mSmlwVTk0S2djTHVRMmUtckxqa2pESldGSTl6UkUzYnd0V3ROZXh5Z0ZnODNLYWdvX0J3Vzd2SQ==","email":"chetan@prodevans.com"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPEY7EfhH3uFvh1mGqjvBTRjoKjVbdkHJH8fhuQHUw8eycp7fgYL8xUDADHoQE9HND3uT4A1BeU3TdCpXFTYApNmMnYm3zFXvD9IqSyAarofsYi8KCPIw7gAXBdSBUZKOWCfiUnMAqo/tXKpiQ2Hlwoi049R67hrR0URYq4Y+c3u5KIN4UPxGbRLxJQRP4NSsRVSz7mSkX40wiHWNjYVrHSEdw4Kiu9UgKklU2JAYPl50VJxZ+wZamNUBlC9e11AD0h/HAQyjoi3b2ao6l8GJZPV4qy5HBWGGsZoqpUv+R+LRD4CrvYgiRWYkXmJ1JW7RhM83V39n2u/D+tl47DFwP redhat@bastion.example.com'   

